"use client";

import { ShieldCheck } from "lucide-react";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";

interface RecommendedActionsProps {
  actions: string[];
}

export function RecommendedActions({ actions }: RecommendedActionsProps) {
  if (!actions || actions.length === 0) return null;

  return (
    <Card className="border-teal-200 bg-gradient-to-b from-teal-50/30 to-white shadow-xs">
      <CardHeader className="p-4 border-b border-teal-100 flex flex-row items-center justify-between">
        <div>
          <CardTitle className="text-sm font-bold text-slate-900 flex items-center gap-2">
            <ShieldCheck className="size-4 text-teal-600" />
            <span>Recommended Infection Control Interventions</span>
          </CardTitle>
          <p className="text-xs text-slate-500 mt-0.5">
            Automated clinical containment protocol recommendations generated by LangGraph Risk Agent
          </p>
        </div>
      </CardHeader>

      <CardContent className="p-4 space-y-2.5">
        {actions.map((action, idx) => (
          <div
            key={idx}
            className="flex items-start gap-3 p-3 rounded-xl bg-white border border-slate-200/80 shadow-xs"
          >
            <div className="flex size-6 items-center justify-center rounded-md bg-teal-600 text-white font-bold text-xs shrink-0 mt-0.5">
              {idx + 1}
            </div>
            <div className="text-xs text-slate-800 font-medium leading-relaxed">
              {action}
            </div>
          </div>
        ))}
      </CardContent>
    </Card>
  );
}
