"""add_lab_report_antibiotics_table

Revision ID: a68d82617155
Revises: 0ab6edf81f2d
Create Date: 2026-08-15 00:12:00.142811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a68d82617155'
down_revision: Union[str, Sequence[str], None] = '0ab6edf81f2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_report_antibiotics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lab_report_id', sa.Integer(), nullable=False),
    sa.Column('antibiotic', sa.String(length=128), nullable=False),
    sa.Column('result', sa.String(length=64), nullable=False),
    sa.Column('mic', sa.String(length=64), nullable=True),
    sa.Column('interp', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['lab_report_id'], ['lab_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_report_antibiotics_id'), 'lab_report_antibiotics', ['id'], unique=False)
    op.create_index(op.f('ix_lab_report_antibiotics_lab_report_id'), 'lab_report_antibiotics', ['lab_report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lab_report_antibiotics_lab_report_id'), table_name='lab_report_antibiotics')
    op.drop_index(op.f('ix_lab_report_antibiotics_id'), table_name='lab_report_antibiotics')
    op.drop_table('lab_report_antibiotics')
    # ### end Alembic commands ###
